export * from './TableInspecciones';
export * from './actas/periodicas/version_07/DatosUsuario';
export * from './actas/periodicas/version_07/EvalRecintosTablaSimple';
export * from './actas/periodicas/version_07/Header';
export * from './actas/periodicas/version_07/InformacionGeneral';
export * from './actas/periodicas/version_07/SeccionIsometricos';
export * from './actas/periodicas/version_07/TrazaVacioInterno';
export * from './actas/periodicas/version_07/TrazabilidadMatriz';
export * from './index';
